### ISSUE TITLE
Syncing recipes always add the version to the name

### ISSUE THREAD

**Issue by damnjanovictanja** [solvebio/solvebio-python#381]
## Bug description and steps to reproduce

I have exported recipes using the `solvebio-recipes export` command, changed the expression, and tried to sync that recipe, without changing the version using the following command: 
```
solvebio-recipes --api-host="https://solvebio.api-stag.solvebio.com" sync --all import_recipe.yml
Logged-in as: Tatjana
Are you sure you want to create Test Recipe (v1.0.0) (v1.0.0) recipe? [y/N]: 
```

The script tried to create a new recipe and add a version to its name, even if the version is already there.
The workaround here is to delete the version from the name and then to try syncing.

One other thing that I have noticed is that all recipes are exported with a field `is_public` set to 'True', even if they are not.

## Additional Context

`import_recipe.yaml` file:

```
recipes:
- name: Test Recipe (v1.0.0)
  description: Gets the protein change from the variant field
  template_type: recipe
  is_public: False
  version: 1.0.0
 . . . 
```
